### ISSUE TITLE
How do I get additional rings?

### ISSUE THREAD

**Issue by Nova-Katt** [Dplayend/Just-Potion-Rings#1]
Weird title, I know. But it's about this part:
"even if you install a mod who adds more effects Just Potion Rings will add more rings with the new mob effects"
Looking in the EMI index I currently have 71 rings in the game, from Ring of Slowness, Ring of Jump Boost, to Ring of Cat Anxiety and Ring of Lava Vision, and so on.

But acquiring them is a mystery.
According to the wiki there is a recipe for 9 of the vanilla rings, which EMI agrees on.
3 vanilla rings are found in loot chests according to the wiki, which EMI Loot doesn't mention.
And everything else? Mystery.
The curse rings with bad effects, the other modded potion effects, how do you actually get those?
There is no info about that.

**Comment by Dplayend** [comment]
Well, the idea about the other rings is for modpack developers (or having fun in the creative mode). The base mod has 13 ways to get 13 types of rings in a vanilla way so to speak, I did it this way so that there were no broken mechanics, on the other hand if there is someone who is making a pack of mods including Just Potion Rings, the idea is that it can implement crafts or other types of ways to obtain the rings trying to make the game as balanced as possible
